// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrjbruifzxpshzxpyowv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyamJydWlmenhwc2h6eHB5b3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTI2OTcsImV4cCI6MjA3Mzk2ODY5N30.4y-7ru77lRetYF6MFvzRcDKgVoaYdzBPUjp15Ap1WSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});